name: tattoo_appointment
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  easy_sticky_header: ^1.1.1

  # State Management
  flutter_bloc: ^8.1.5
  get_it: ^7.7.0

  # Localizations
  easy_localization: ^3.0.6

  # Serialization
  equatable: ^2.0.5

  # Cache
  hive: ^2.2.3

  # Utils
  path_provider: ^2.1.3
  google_fonts: ^6.2.1

  # Modules
  core:
    path: modules/core

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/images/landscape/
